// <auto-generated />
using System;
using Asistencia.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asistencia.Data.Migrations
{
    [DbContext(typeof(MarcacionAsistenciaDbContext))]
    partial class MarcacionAsistenciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.AsignacionTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsVigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_vigente");

                    b.Property<DateTime?>("FechaFinVigencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin_vigencia");

                    b.Property<DateTime>("FechaInicioVigencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio_vigencia");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.HasKey("Id");

                    b.HasIndex("TrabajadorId");

                    b.HasIndex("TurnoId");

                    b.ToTable("ASIGNACIONES_TURNO", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.AsistenciaResumenDiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_resumen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EstadoAsistencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_asistencia");

                    b.Property<DateTime>("FechaAsistencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_asistencia");

                    b.Property<DateTime?>("HoraEntradaReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_entrada_real");

                    b.Property<DateTime?>("HoraEntradaTeorica")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_entrada_teorica");

                    b.Property<DateTime?>("HoraSalidaReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_salida_real");

                    b.Property<DateTime?>("HoraSalidaTeorica")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_salida_teorica");

                    b.Property<int>("MinutosExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("minutos_extra");

                    b.Property<int>("MinutosTardanza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("minutos_tardanza");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.HasKey("Id");

                    b.HasIndex("TrabajadorId", "FechaAsistencia")
                        .IsUnique();

                    b.ToTable("ASISTENCIA_RESUMEN_DIARIO", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.CalendarioFeriado", b =>
                {
                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsFeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_feriado");

                    b.HasKey("Fecha");

                    b.ToTable("CALENDARIO_FERIADOS", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraFinRefrigerio")
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_fin_refrigerio");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_inicio");

                    b.Property<TimeSpan?>("HoraInicioRefrigerio")
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_inicio_refrigerio");

                    b.Property<int>("HorarioTurnoId")
                        .HasColumnType("int")
                        .HasColumnName("id_horario_turno");

                    b.Property<bool>("SalidaDiaSiguiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("salida_dia_siguiente");

                    b.Property<int>("TiempoRefrigerioMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("tiempo_refrigerio_minutos");

                    b.HasKey("Id");

                    b.HasIndex("HorarioTurnoId");

                    b.ToTable("HORARIOS_DETALLE", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_horario_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreHorario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_horario");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.ToTable("HORARIOS_TURNO", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Justificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_justificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoAdjuntoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("documento_adjunto_url");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<DateTime>("FechaJustificada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_justificada");

                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("TipoJustificacionId")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_justificacion");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("UsuarioAutoriza")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usuario_autoriza");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("TipoJustificacionId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("JUSTIFICACIONES", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MaestroEstado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("color_hex");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("GrupoEstado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("grupo_estado");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id");

                    b.ToTable("MAESTRO_ESTADOS", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MarcacionAsistencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_marcacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("foto_url");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitud");

                    b.Property<string>("TipoMarcacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tipo_marcacion");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<bool?>("UbicacionValida")
                        .HasColumnType("bit")
                        .HasColumnName("ubicacion_valida");

                    b.HasKey("Id");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("MARCACIONES_ASISTENCIA", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidosNombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos_nombres");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo_personal");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("dni");

                    b.Property<string>("TelefonoPersonal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono_personal");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("PERSONAS", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.SolicitudHorasExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_solicitud");

                    b.Property<decimal>("HorasSolicitadas")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("horas_solicitadas");

                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdJefeAprueba")
                        .HasColumnType("int")
                        .HasColumnName("id_jefe_aprueba");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdJefeAprueba");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("SOLICITUDES_HORAS_EXTRA", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.SucursalCentro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("es_activo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("direccion");

                    b.Property<decimal?>("LatitudCentro")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitud_centro");

                    b.Property<decimal?>("LongitudCentro")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitud_centro");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_sucursal");

                    b.Property<int?>("PerimetroM")
                        .HasColumnType("int")
                        .HasColumnName("perimetro_m");

                    b.HasKey("Id");

                    b.HasIndex("NombreSucursal")
                        .IsUnique();

                    b.ToTable("SUCURSAL", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.TipoJustificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_justificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_tipo");

                    b.Property<bool>("RequiereAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_adjunto");

                    b.HasKey("Id");

                    b.HasIndex("NombreTipo")
                        .IsUnique();

                    b.ToTable("TIPO_JUSTIFICACION", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("Id");

                    b.HasIndex("NombreTipo")
                        .IsUnique();

                    b.ToTable("TIPO_TURNO", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaDepartamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("area_departamento");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cargo");

                    b.Property<string>("CorreoCorporativo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo_corporativo");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ingreso");

                    b.Property<bool>("HorasExtraConf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("horas_extra_conf");

                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("id_estado");

                    b.Property<int?>("JefeInmediatoId")
                        .HasColumnType("int")
                        .HasColumnName("id_jefe_inmediato");

                    b.Property<bool>("MarcajeEnZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("marcaje_en_zona");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<decimal?>("SueldoBruto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("sueldo_bruto");

                    b.Property<string>("TelefonoCorporativo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono_corporativo");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("JefeInmediatoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.HasIndex("UserId");

                    b.ToTable("TRABAJADORES", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nombre_codigo");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_turno");

                    b.Property<int?>("ToleranciaIngreso")
                        .HasColumnType("int")
                        .HasColumnName("tolerancia_ingreso");

                    b.Property<int?>("ToleranciaSalida")
                        .HasColumnType("int")
                        .HasColumnName("tolerancia_salida");

                    b.HasKey("Id");

                    b.HasIndex("NombreCodigo")
                        .IsUnique();

                    b.HasIndex("TipoTurnoId");

                    b.ToTable("TURNOS", (string)null);
                });

            modelBuilder.Entity("Asistencia.Data.Entities.UserEntites.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_refresh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("REFRESH_TOKENS");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.UserEntites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.AsignacionTurno", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trabajador");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.AsistenciaResumenDiario", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioDetalle", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioTurno", "HorarioTurno")
                        .WithMany("HorariosDetalle")
                        .HasForeignKey("HorarioTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioTurno");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioTurno", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Turno", "Turno")
                        .WithMany("HorariosTurno")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Justificacion", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MaestroEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.TipoJustificacion", "TipoJustificacion")
                        .WithMany()
                        .HasForeignKey("TipoJustificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("TipoJustificacion");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MarcacionAsistencia", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.SolicitudHorasExtra", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MaestroEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", null)
                        .WithMany()
                        .HasForeignKey("IdJefeAprueba");

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.MaestroEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Trabajador", "JefeInmediato")
                        .WithMany()
                        .HasForeignKey("JefeInmediatoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.SucursalCentro", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.HasOne("Asistencia.Data.Entities.UserEntites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("JefeInmediato");

                    b.Navigation("Persona");

                    b.Navigation("Sucursal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Turno", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.MarcacionAsistenciaEntites.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.UserEntites.RefreshToken", b =>
                {
                    b.HasOne("Asistencia.Data.Entities.UserEntites.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.HorarioTurno", b =>
                {
                    b.Navigation("HorariosDetalle");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.MarcacionAsistenciaEntites.Turno", b =>
                {
                    b.Navigation("HorariosTurno");
                });

            modelBuilder.Entity("Asistencia.Data.Entities.UserEntites.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
